export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_PROFILE_DETAIL = "FETCH_PROFILE_DETAIL";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const FETCH_ITEM_DETAIL = "FETCH_ITEM_DETAIL";
export const FILTER_ITEMS = "FILTER_ITEMS";
export const POST_BIDDINGS = "POST_BIDDINGS";
